language: bash
sudo: required
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
before_install:
- |
  if [[ "${TRAVIS_COMMIT_MESSAGE}" == "[gitflow]"* ]] && [[ "${TRAVIS_BRANCH}" != v[0-9]* ]]; then
    travis_terminate 0
  fi
before_script:
- cp .travis.settings.xml $HOME/.m2/settings.xml
script:
- |
  if [[ "${TRAVIS_BRANCH}" == release-* ]]; then
    QUALIFIER=-frozen-${TRAVIS_BUILD_NUMBER}
  elif [[ "${TRAVIS_BRANCH}" == "development" ]]; then
    QUALIFIER=-dev-${TRAVIS_BUILD_NUMBER}
  elif [[ "${TRAVIS_BRANCH}" == v[0-9]* ]]; then
    QUALIFIER=""
  else
    QUALIFIER=-${TRAVIS_BRANCH}-${TRAVIS_BUILD_NUMBER}
  fi && ./.travis.scripts/mvn.sh build-helper:parse-version versions:set -DgenerateBackupPoms=false -DnewVersion='${parsedVersion.majorVersion}.${parsedVersion.minorVersion}.${parsedVersion.incrementalVersion}'${QUALIFIER}
- "./.travis.scripts/mvn.sh -Dmaven.site.skip=true clean verify -B -e -V"
after_success:
- |
  if [[ "${TRAVIS_BRANCH}" == v[0-9]* ]] || [[ "${TRAVIS_BRANCH}" == release-* ]] || [[ "${TRAVIS_BRANCH}" == "development" ]]; then
    ./.travis.scripts/mvn.sh sonar:sonar
  fi
- |
  if [[ "${TRAVIS_BRANCH}" == v[0-9]* ]]; then
    ./.travis.scripts/mvn.sh -P github-site site  fi
deploy:
  provider: script
  script: "./.travis.scripts/mvn.sh -Dmaven.site.skip=true -P stage-devel-bintray
    deploy"
  skip_cleanup: true
  on:
    all_branches: true
branches:
  except:
  - gh-pages
  - master
env:
  matrix:
    secure: IwJmZqpenb7L+WHNaTC5u+cWQhp6RDCft7ngEAHbssZbO4YlehylgqTnj72NqPf2ml3h0N9brzfJURIBo1jrDSyoIZ1c3Z0lGTfTUVS0pzdJYNEe5nrsSE4OYbic06Vk/G+5HET5KQgmMB1+QfOE40z4AD5UK3hCVX9nx6JxiliUXS5o5pBCdFOjFotLjK5RRbSWTgPJ5/NhV6vZUAmk1e6GOUTeajnJoBO5SVRLl2Q+o8kL6rXxAxew5scIkSEm5Ug4WTQCb40FZkk3J1Lszfa0XdSv1e3b8MMkoNeVwvoG3G5yzKxXaIfJ2gX5fubOm408fmKka6nO7cbT8qo9pFDdSSa75uygm4d3Clx65yAhod11Nqy3/oZNYFe/fvF2h/4CyhFB3lr5f1xRjcOWP6AOZsR9v1TjNjhdMA9KSCIbD2fGpLYC+X719tc+b8AUkwKOh1Vl0fnX6U/Zp1F2MRlzzv2gElLQzGClaPLrcJ12TxJIfA6RFjq5Be/SXG/P+m5a6I+VSjo/XgQB+bhFS5Ll4d9R0+hgaE9ShXDLfFSuIT/8sNvCjqVKkyRFuApmMd6siePHrxHYh4CD6Hv0GP4qDaExCbVQnWTjlRb/JR8ZOkX75d3AMq+54qo9sLuS1u/1Jwfcl0iMULylIl/C61TfdLnWRhgMxu37UFsoIzg=
  global:
  - secure: wqXmpvLuhlzQQq1Uqc9gSxmBGfmdB+SLhHrIBKwyGAPz+6ELRnCfzJ2g3yiJXqxJ5aVjCb+QAeZWY07kpEcGHj6LqsM3QqCUUDxoEV+nrS0vxmCNEXst/jIvcLBWQRQxdeosqCkJJm/kh2DCckANxbspMinVO2ZUDJj2k54oiXoMBqT3m2Cq4ezx+ITKDT8XC5I6J7NDHMXUcIId7GpJO1U9FExpBeGvEKbs9l1FYB1XHU9wtIaHc5E4YoQD9KkVqQlh8L/rQ2V8cmW+d3Mipzj6YVqlFchwn9EJhN9DmXm9IsaksncDm0MoFdSJHO6ghiTNU4eesI5bSxr0C3HHBiSvuulti6o29AIYOv9HRkUQLmkY+MU78B4J75D1IPgqP/A5c+hr++k9vfx6nRawz9begJ61jR0mU9OF0B3xaFJNBEz/4jAhCfS1ed2PAd3MwxACrr9aZa5eKx9nBYhc8aovvRbJXcvJWXLzdum3te0sXsb48VSQkUY1K4kVPU14JJFu6mwQPeTvV1IeaxYkYLh1FVDumi5eNv/xBGjOkhcXxp47MXYNpHy5IkvkR2GIiARPK09h2gswEAhDCs0v8zuXH4PTIXRTcNBujwnOAssWEU8pDLgrJVUpdFDbb250YaUXugklEUimJWP3G3FCRqTro4X60Fe2bhg6v78v/dc=
  - secure: i2eZpXbdGEqIwoCUn+SjY6V93BDtABxP+X7wCpHQsTiqjS4L7pO/u16P2XXDKPEGF46uCDKW3ouwSNMZR4szdYk3atyoTXmJR+XNcXEbeGiveetD6ZlhCUMWKP7HIeD9Ff5BX1+W0cIIPVPmZnhkCQJtby0TBHWq62bJAmX+GhOdwaapHq9Z+cafNhWu+qHagGK+GsWtzfLaBs4Napey2DQxZ07Rlnn+8vlMT/5QnDCwqa+825DkIa0gJndeX2y83oPyqLThe5cl6pAPyfn3BdT9U/uiMcX/3l6AU1MkAnk7/RXovcwpcyToNMfn3I5O+wz4VjEuz41EQ9yh0bu/pJAP9R5aIud/jlqwBv1oOrOBcm0TPgpuxNPnh8PJN+t3jimIvhFl0evg9mq6YlUCA5gbPWMlLTcwvlQ7pwCv9kbukef4kXqsOtkLTuFBiJto/MEVdsIkMRdJ2p47YYTuElb3eXWxB2Zh4EXDHzWiZ6QL/Npvpo3OFlk+T5GFPrSqR9+YrZrpn1uI5exLlEgoN3hkwMZBwyALGkid0ZGnfIVorOyOBVhvEgVNjlFGLPBm/cOWlpuj2kWfxGYtt8AqMS9tfdylv3lWFnpR8692U1VpKXfcG57jUeeBuZRARIXp6L8qR5MiUpn/H4ibgSiYUZVZiCUfEU+9e/Da7zdglOc=
  - secure: D0ZU760z2fNm6MdE4FjB5ydGapaQLeEwPQ2+sdeO/ISyi/ai8ZoX2HKY2BJvnC4nXBjvmduHbKJA2ZmQRK5NdkwllgYFrgmXlHnK3do/ioCLWF45zOxBEw5TIcuJ+DOU57L2OVBdkwPbdwSWOr+n0HgdWtqYJtwK8w/Q1RYCvrneLFXRYApdV/OXAuslrRvga2JbENaSt0zSkzSavbmRWT8bSbtLGzOnVm1aJC9riRcSnCOebRIofLnebAagzE1WWxVKuF0R3RK1cNeOzzWVL/twyICqO74bUJNOR3GX3tFxSCkQyOdHh0ntLLE+ElWSTa8ZsxPNU8FRo2qr94VR+a7nzvDqn3mvRkExshdDD7P6fMU23gDpldNKvYSUkwaMGrOowQfpm2pgVW2wIOa1GtDWbEJ9uRDXCnCBEkUzEFY9jz+K1i8SJ6ONas2PwAFMTtRgx+oqgLqjMzzzBL4o2wz9IhvRwBFkbYpk5zJT5SnCVVUGhIcZa+OExjGS9Dz99izgw6G8KVaf0tX55thQXbDnVmuIP1rGQLAaLd4OuCghkcH12RsKpiTV1Mw8btTdvkP26ra0kdY7u2GcoLVs/XgZ3ywzI/Emb8297aB59bFIXfzF0lJXE9e6pNqkbG3dRDW630oQu9UmEsStde/HvNAR5K0XTB6qbJE//Flt15M=
  - secure: CgP4HoRuWSzbHHqIwYr2DMJl5iA7zh2oz7nwWkVngZb35+QMW6dElwKHIUVURZDWy6kyY35Gh8asiJy7FvFfnlvKy9xtuneqdDdY6d5BrgRfjkH21tXvUET2ReFocqkwJoO2zYWYXuQ4kkQ7TDN3QnutZPAswip9EuyvUaa61m0W4ARG5uG7wieD/kzz7/K8RDX5qJOTBgE8XOQzgEz2tecmaxhcjXREgeof/q9cp8NLY4VYisNKh+cVXa6augEM5E0ZEGhrwimYjONVP/dvt8pUXZLMWIrQ3dmRaGJO/6v00rFH9HN4b2umEvu+Ko7/D5qlTqm3CiMZvDn5ED2OkjKacA/9XhOBAai0DP0aGyKJibS9EThuHGeuT1V5S+RQB8MHfzg385JX1fSvvp6waEbUtb1/nx9002vy45DtwG5UzVE+jJ+UB7dKwtku34tTXvMk38PozdByLvrOVEBjE7+YfGFYyB/JQcO9d8urgbY9U1O/SUKf2ls6SHSxcgi5WhebkA5YGm11RSYajBuj/Mb9Ft+v2t9pfLE7Et2WnANwftxC5sAbqRZjZEs4ExPKgDLZOVUto0sEOhFJSH/QiFD3ISgOZ4dDDs+8Zueb7e3E8yVGm5PUpHVd1QSj33q3HAxZJMD0/b2zAWUEvcEmlJ8fL/6+Xr2n+/NpJDimJfg=
